module.exports = {
    account: {
        type: "QUERY",
        table: "Account",
        responseKey: "Account",
        isMaster: true,
    },
    customer: {
        type: "QUERY",
        table: "Customer",
        responseKey: "Customer",
        isMaster: true,
    },
    vendor: {
        type: "QUERY",
        table: "Vendor",
        responseKey: "Vendor",
        isMaster: true,
    },
    item: {
        type: "QUERY",
        table: "Item",
        responseKey: "Item",
        isMaster: true,
    },
    class: {
        type: "QUERY",
        table: "Class",
        responseKey: "Class",
        isMaster: true,
    },
    taxrate: {
        type: "QUERY",
        table: "TaxRate",
        responseKey: "TaxRate",
        isMaster: true,
    },
    companycurrency: {
        type: "QUERY",
        table: "CompanyCurrency",
        responseKey: "CompanyCurrency",
        isMaster: true,
    },
    invoice: {
        type: "QUERY",
        table: "Invoice",
        responseKey: "Invoice",
        dateField: "TxnDate",
    },
    bill: {
        type: "QUERY",
        table: "Bill",
        responseKey: "Bill",
        dateField: "TxnDate",
    },
    payment: {
        type: "QUERY",
        table: "Payment",
        responseKey: "Payment",
        dateField: "TxnDate",
    },
    billpayment: {
        type: "QUERY",
        table: "BillPayment",
        responseKey: "BillPayment",
        dateField: "TxnDate",
    },
    vendorcredit: {
        type: "QUERY",
        table: "VendorCredit",
        responseKey: "VendorCredit",
        dateField: "TxnDate",
    },
    creditmemo: {
        type: "QUERY",
        table: "CreditMemo",
        responseKey: "CreditMemo",
        dateField: "TxnDate",
    },
    journalentry: {
        type: "QUERY",
        table: "JournalEntry",
        responseKey: "JournalEntry",
        dateField: "TxnDate",
    },
    term: {
        type: "QUERY",
        table: "Term",
        responseKey: "Term",
        dateField: "TxnDate",
    },
    transfer: {
        type: "QUERY",
        table: "Transfer",
        responseKey: "Transfer",
        dateField: "TxnDate",
    },
    deposit: {
        type: "QUERY",
        table: "Deposit",
        responseKey: "Deposit",
        dateField: "TxnDate",
    },
    estimate: {
        type: "QUERY",
        table: "Estimate",
        responseKey: "Estimate",
        dateField: "TxnDate",
    },
    salesreceipt: {
        type: "QUERY",
        table: "SalesReceipt",
        responseKey: "SalesReceipt",
        dateField: "TxnDate",
    },
    purchaseorder: {
        type: "QUERY",
        table: "PurchaseOrder",
        responseKey: "PurchaseOrder",
        dateField: "TxnDate",
    },
};
